//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumVideoHinhAnh
    {
        public int IdVideoHinhAnh { get; set; }
        public string TenVideoHinhAnh { get; set; }
        public string Mota { get; set; }
        public string Files { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<bool> Show { get; set; }
        public Nullable<int> IdAlbum { get; set; }
        public string LinkNhung { get; set; }
    
        public virtual LoaiAlbum LoaiAlbum { get; set; }
    }
}
