//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauTraLoi
    {
        public int MaCTL { get; set; }
        public string ND { get; set; }
        public Nullable<bool> Show { get; set; }
        public Nullable<int> MaCH { get; set; }
        public string MaND { get; set; }
    
        public virtual CauHoi CauHoi { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
