//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitietMenu
    {
        public int ID { get; set; }
        public Nullable<int> IdMenu { get; set; }
        public Nullable<int> IdPage { get; set; }
        public Nullable<int> IdLoaiTin { get; set; }
        public Nullable<int> IdLink { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<int> IdCha { get; set; }
    
        public virtual LinkTuDo LinkTuDo { get; set; }
        public virtual LinkTuDo LinkTuDo1 { get; set; }
        public virtual LoaiTin LoaiTin { get; set; }
        public virtual LoaiTin LoaiTin1 { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual Menu Menu1 { get; set; }
        public virtual Page Page { get; set; }
        public virtual Page Page1 { get; set; }
    }
}
