//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int Ma { get; set; }
        public string Ten { get; set; }
        public string DC { get; set; }
        public string Phone { get; set; }
        public string Tel { get; set; }
        public string Mota { get; set; }
        public string Logan { get; set; }
        public string Email { get; set; }
    }
}
