//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaXayDung.Models
{
    using System;
    
    public partial class LayDanhSachTinTucTheoLoai_Result1
    {
        public string TenT { get; set; }
        public string MT { get; set; }
        public string H { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> Xem { get; set; }
        public int MaT { get; set; }
    }
}
