//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public int MaLH { get; set; }
        public string Ten { get; set; }
        public string ND { get; set; }
        public string DC { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<bool> Show { get; set; }
        public Nullable<bool> TrangThaiXem { get; set; }
    }
}
