//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienKet
    {
        public int MaLK { get; set; }
        public string TenLK { get; set; }
        public string LinkLK { get; set; }
        public string LogoLK { get; set; }
        public bool Show { get; set; }
    }
}
