//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaXayDung.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KhoaXayDungEntities : DbContext
    {
        public KhoaXayDungEntities()
            : base("name=KhoaXayDungEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlbumVideoHinhAnh> AlbumVideoHinhAnhs { get; set; }
        public virtual DbSet<CauHoi> CauHois { get; set; }
        public virtual DbSet<CauTraLoi> CauTraLois { get; set; }
        public virtual DbSet<ChitietMenu> ChitietMenus { get; set; }
        public virtual DbSet<Info> Infoes { get; set; }
        public virtual DbSet<LienHe> LienHes { get; set; }
        public virtual DbSet<LienKet> LienKets { get; set; }
        public virtual DbSet<LinkTuDo> LinkTuDoes { get; set; }
        public virtual DbSet<LoaiAlbum> LoaiAlbums { get; set; }
        public virtual DbSet<LoaiSlide> LoaiSlides { get; set; }
        public virtual DbSet<LoaiTin> LoaiTins { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<QCLink> QCLinks { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<Slide> Slides { get; set; }
        public virtual DbSet<ThongKe> ThongKes { get; set; }
        public virtual DbSet<Tin> Tins { get; set; }
    
        public virtual ObjectResult<LayDanhSachTinTucTheoLoai_Result1> LayDanhSachTinTucTheoLoai(Nullable<int> idLoai)
        {
            var idLoaiParameter = idLoai.HasValue ?
                new ObjectParameter("idLoai", idLoai) :
                new ObjectParameter("idLoai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDanhSachTinTucTheoLoai_Result1>("LayDanhSachTinTucTheoLoai", idLoaiParameter);
        }
    }
}
