//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QCLink
    {
        public int MaQC { get; set; }
        public string TenQC { get; set; }
        public string Link { get; set; }
        public string H { get; set; }
        public Nullable<bool> Show { get; set; }
        public Nullable<int> STT { get; set; }
        public string MaND { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
