//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int MaSlide { get; set; }
        public int MaLoai { get; set; }
        public string TenSlide { get; set; }
        public string AnhSlide { get; set; }
        public string LinkSide { get; set; }
        public string MoTaSlide { get; set; }
        public bool Show { get; set; }
    
        public virtual LoaiSlide LoaiSlide { get; set; }
        public virtual LoaiSlide LoaiSlide1 { get; set; }
    }
}
