//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaXayDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tin
    {
        public int MaT { get; set; }
        public string TenT { get; set; }
        public string MT { get; set; }
        public string ND { get; set; }
        public string H { get; set; }
        public string F { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> Xem { get; set; }
        public Nullable<int> MaLT { get; set; }
        public string Link { get; set; }
        public Nullable<bool> Show { get; set; }
        public string MaND { get; set; }
        public Nullable<System.DateTime> ThoiGianDienRa { get; set; }
        public string DiaDiem { get; set; }
    
        public virtual LoaiTin LoaiTin { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
